// SPDX-License-Identifier: Apache-2.0
//! Raw syscall wrapper - uses `ud2` (CPU #UD exception, IDT vector 6).
//!
//! This is the only place in the SDK that issues raw assembly.
//! Calling convention matches `syscall_entry.rs` / `ud2_syscall_entry`:
//!   rax = syscall number, rdi = arg0, rsi = arg1, rdx = arg2.
//!
//! On AMD GX-420GI (Jaguar/Puma+) both the SYSCALL instruction and software
//! interrupts (`int N`) silently stall the core from ring-3 with no exception
//! or visible failure.  `ud2` (0x0F 0x0B) triggers a hardware #UD exception -
//! generated by the CPU decoder, not the software interrupt pathway - and
//! dispatches via IDT[6] on all x86-64 hardware.
//!
//! The kernel ud2 handler uses rcx as the 4th arg (like the SYSCALL path),
//! and syscall_handler may clobber any caller-saved register.  All must be
//! declared inout/lateout so the compiler never assumes they survive the call.

/// Issue a three-argument syscall via `ud2` and return the i64 result.
///
/// # Safety
/// Caller must pass valid arguments for the given syscall number.
#[cfg(target_arch = "arm")]
#[inline]
pub(crate) unsafe fn raw_syscall(nr: u64, a0: u64, a1: u64, a2: u64) -> i64 {
    // ARMv7 syscall mechanism: `svc #0`, matching the kernel's SVC entry (arch/arm/syscall.rs).
    // The kernel ABI takes the number and three args in r0-r3 as single 32-bit registers (a u64
    // parameter would be a register PAIR on 32-bit ARM); every argument on this arch - pointer,
    // handle, length - fits in 32 bits. The i64 result comes back in r0:r1.
    let lo: u32;
    let hi: u32;
    // SAFETY: `svc #0` traps to the kernel SVC handler, which preserves callee-saved registers and
    // returns the i64 result in r0:r1. r0-r3 are the ABI inputs (clobbered by the handler); r12 is
    // caller-saved. No VFP clobber list (soft-float target has none), so the clobbers are listed by hand.
    unsafe {
        core::arch::asm!(
            "svc #0",
            inout("r0") nr as u32 => lo,
            inout("r1") a0 as u32 => hi,
            inout("r2") a1 as u32 => _,
            inout("r3") a2 as u32 => _,
            lateout("r12") _,
            options(nostack),
        );
    }
    ((hi as u64) << 32 | lo as u64) as i64
}

#[cfg(target_arch = "x86_64")]
#[inline]
pub(crate) unsafe fn raw_syscall(nr: u64, a0: u64, a1: u64, a2: u64) -> i64 {
    let ret: i64;
    // SAFETY: `ud2` triggers a hardware #UD exception (IDT[6]) which transitions
    // to ring-0 via ud2_syscall_entry and returns via iretq.  The CPU switches
    // to kernel stack (TSS.rsp0) on the exception, so the user stack is untouched
    // - options(nostack) is correct.  ud2_syscall_entry advances RIP by 2 before
    // iretq so control resumes at the instruction after the ud2 opcode.
    unsafe {
        core::arch::asm!(
            "ud2",
            inout("rax") nr => ret,
            inout("rdi") a0 => _,
            inout("rsi") a1 => _,
            inout("rdx") a2 => _,
            lateout("rcx") _,   // used as 4th arg in ud2_syscall_entry; may be clobbered
            lateout("r10") _,   // used as scratch in ud2_syscall_entry
            lateout("r11") _,   // caller-saved; syscall_handler may modify
            lateout("r8")  _,
            lateout("r9")  _,
            options(nostack),
        );
    }
    ret
}
