// SPDX-License-Identifier: Apache-2.0
//! Raw syscall wrapper - uses `ud2` (CPU #UD exception, IDT vector 6).
//!
//! This is the only place in the SDK that issues raw assembly.
//! Calling convention matches `syscall_entry.rs` / `ud2_syscall_entry`:
//!   rax = syscall number, rdi = arg0, rsi = arg1, rdx = arg2.
//!
//! On AMD GX-420GI (Jaguar/Puma+) both the SYSCALL instruction and software
//! interrupts (`int N`) silently stall the core from ring-3 with no exception
//! or visible failure.  `ud2` (0x0F 0x0B) triggers a hardware #UD exception -
//! generated by the CPU decoder, not the software interrupt pathway - and
//! dispatches via IDT[6] on all x86-64 hardware.
//!
//! The kernel ud2 handler uses rcx as the 4th arg (like the SYSCALL path),
//! and syscall_handler may clobber any caller-saved register.  All must be
//! declared inout/lateout so the compiler never assumes they survive the call.

/// Issue a three-argument syscall via `ud2` and return the i64 result.
///
/// # Safety
/// Caller must pass valid arguments for the given syscall number.
#[inline]
pub(crate) unsafe fn raw_syscall(nr: u64, a0: u64, a1: u64, a2: u64) -> i64 {
    let ret: i64;
    // SAFETY: `ud2` triggers a hardware #UD exception (IDT[6]) which transitions
    // to ring-0 via ud2_syscall_entry and returns via iretq.  The CPU switches
    // to kernel stack (TSS.rsp0) on the exception, so the user stack is untouched
    // - options(nostack) is correct.  ud2_syscall_entry advances RIP by 2 before
    // iretq so control resumes at the instruction after the ud2 opcode.
    unsafe {
        core::arch::asm!(
            "ud2",
            inout("rax") nr => ret,
            inout("rdi") a0 => _,
            inout("rsi") a1 => _,
            inout("rdx") a2 => _,
            lateout("rcx") _,   // used as 4th arg in ud2_syscall_entry; may be clobbered
            lateout("r10") _,   // used as scratch in ud2_syscall_entry
            lateout("r11") _,   // caller-saved; syscall_handler may modify
            lateout("r8")  _,
            lateout("r9")  _,
            options(nostack),
        );
    }
    ret
}
