// SPDX-License-Identifier: Apache-2.0
//! Raw syscall wrapper - **one `raw_syscall` per ISA**, and the whole of the SDK's raw assembly.
//!
//! This is the seam CLAUDE.md 18.1 names by hand: "the syscall ABI (`raw_syscall`, inline `asm!`)".
//! It is one of the few places where `#[cfg(target_arch)]` is the RIGHT question rather than a board
//! fact in disguise - a trap instruction and its register convention are properties of the
//! instruction set and of nothing else. Four bodies, four ISAs, no shared code between them.
//!
//! | ISA | trap | number + args |
//! |-----|------|---------------|
//! | arm (ARMv7-A) | `svc #0` | r0-r3, **each 32 bits** - see the truncation note on that body |
//! | aarch64 | `svc #0` | **x16** = number, x0-x2 = args   (NOT x8 - see the note on the aarch64 body) |
//! | riscv64 | `ecall` | a7 = number, a0-a2 = args |
//! | x86-64 | `ud2` | rax = number, rdi/rsi/rdx = args |
//!
//! **Why x86-64 uses `ud2` rather than `syscall`**, since it is the surprising one: on the AMD
//! GX-420GI (Jaguar/Puma+) both the `SYSCALL` instruction and software interrupts (`int N`) silently
//! stall the core from ring-3, with no exception and no visible failure. `ud2` (0x0F 0x0B) raises a
//! hardware #UD generated by the CPU decoder rather than by the software-interrupt pathway, and
//! dispatches via IDT[6] on all x86-64 hardware. The kernel's `ud2` handler takes a 4th arg in rcx
//! (as the `SYSCALL` path does), and `syscall_handler` may clobber any caller-saved register - all of
//! which must be declared inout/lateout so the compiler never assumes they survive the call.
//!
//! (This header used to be only the paragraph above, written when x86-64 was the only port: it opened
//! "uses `ud2`" and gave the rax/rdi/rsi/rdx convention as though it were the file's, in a file that
//! has carried four incompatible conventions for months.)

/// Issue a three-argument syscall via `ud2` and return the i64 result.
///
/// # Safety
/// Caller must pass valid arguments for the given syscall number.
#[cfg(target_arch = "arm")]
#[inline]
pub(crate) unsafe fn raw_syscall(nr: u64, a0: u64, a1: u64, a2: u64) -> i64 {
    // ARMv7 syscall mechanism: `svc #0`, matching the kernel's SVC entry (arch/arm/syscall.rs).
    // The kernel ABI takes the number and three args in r0-r3 as single 32-bit registers (a u64
    // parameter would be a register PAIR on 32-bit ARM), so each arg is TRUNCATED to u32 here. Every
    // arg the current syscalls pass - pointer, handle, length, cap slot - fits in 32 bits. The ONE
    // exceptions are values that can exceed 32 bits, and each is handled in ITS OWN WRAPPER before it
    // reaches this truncation (userspace-audit A-U1): `recv_timeout` clamps a generic-timer tick count,
    // and the USB-disk wrappers reject an LBA above u32::MAX rather than let it alias onto a real block
    // (`lba_fits_syscall_abi`). This comment previously claimed the timeout was the ONE exception, which
    // was false the moment a u64 LBA started coming through here - so before adding any syscall, check
    // whether an argument can exceed 32 bits and clamp it above, and amend this list when it can.
    // The i64 result comes back in r0:r1.
    let lo: u32;
    let hi: u32;
    // SAFETY: `svc #0` traps to the kernel SVC handler, which preserves callee-saved registers and
    // returns the i64 result in r0:r1. r0-r3 are the ABI inputs (clobbered by the handler); r12 is
    // caller-saved. No VFP clobber list (soft-float target has none), so the clobbers are listed by hand.
    unsafe {
        core::arch::asm!(
            "svc #0",
            inout("r0") nr as u32 => lo,
            inout("r1") a0 as u32 => hi,
            inout("r2") a1 as u32 => _,
            inout("r3") a2 as u32 => _,
            lateout("r12") _,
            options(nostack),
        );
    }
    ((hi as u64) << 32 | lo as u64) as i64
}

/// AArch64: `svc #0`, with the syscall number in `x16` and arguments in `x0`-`x2`.
///
/// The number has to live in a **register**, not in the instruction: `svc #N` encodes `N` as an
/// immediate, so it must be a compile-time constant - fine for a fixed handful of calls, impossible for
/// a `raw_syscall` whose caller picks the number at runtime.
///
/// **`x16`, deliberately NOT `x8`.** Linux uses `x8`, and copying that cost a long debugging session.
/// AAPCS64 makes `x8` the **indirect result register**: a function returning a large struct receives
/// the destination pointer there. `raw_syscall` is `#[inline]`, so the `svc` lands *inside* functions
/// that do exactly that - `recv()` returns a `Message` of about 4 KiB by value - and the syscall number
/// then sits where the return-value destination should be. The symptom was a service `memcpy`ing 4 KiB
/// to an address past the top of its stack, with `x8` holding a stale syscall number.
///
/// Linux gets away with `x8` because its syscalls sit behind a non-inlined wrapper, so `x8` is dead at
/// the boundary. `x16` (IP0) is an ordinary intra-procedure scratch register with no ABI role that can
/// be live across a call, which is what makes it safe here.
///
/// Unlike the 32-bit ARM path above, **nothing is truncated**: the registers are 64-bit, so a `u64`
/// argument passes whole and the `i64` result comes back in a single register. The whole class of
/// bugs that path has to guard against (an LBA or a tick count aliasing when it exceeds 32 bits) does
/// not arise here.
///
/// # Safety
/// Caller must pass valid arguments for the given syscall number.
#[cfg(target_arch = "aarch64")]
#[inline]
pub(crate) unsafe fn raw_syscall(nr: u64, a0: u64, a1: u64, a2: u64) -> i64 {
    let ret: i64;
    // SAFETY: `svc #0` traps to EL1's synchronous-lower-EL vector, which saves the full register set
    // on the kernel stack (SP_EL1, selected by the exception - the user stack is untouched, so
    // `nostack` is correct), services the call, and returns with x0 holding the result. The handler
    // may clobber any caller-saved register, so x0-x3 and the rest of the caller-saved set are
    // declared clobbered rather than assumed to survive.
    unsafe {
        core::arch::asm!(
            "svc #0",
            in("x16") nr,
            inout("x0") a0 => ret,
            inout("x1") a1 => _,
            inout("x2") a2 => _,
            lateout("x3") _,
            lateout("x4") _,
            lateout("x5") _,
            lateout("x6") _,
            lateout("x7") _,
            lateout("x9") _,
            lateout("x10") _,
            lateout("x11") _,
            lateout("x12") _,
            lateout("x13") _,
            lateout("x14") _,
            lateout("x15") _,
            lateout("x17") _,
            lateout("x18") _,
            options(nostack),
        );
    }
    ret
}

/// RISC-V 64: `ecall`, with the syscall number in `a7` and arguments in `a0`-`a2`.
///
/// The platform's own convention, which is what the kernel's `ecall` entry answers
/// (`arch/riscv64/syscall.rs`): number in `a7`, three arguments in `a0`-`a2`, result back in `a0`.
/// Unlike AArch64 there is no register to argue about - `a7` is where every RISC-V ABI in existence
/// puts a syscall number, including SBI, so nothing else can be holding a live value there.
///
/// **Nothing is truncated.** The registers are 64-bit, so a `u64` argument passes whole and the
/// `i64` result comes back in one register. The class of bug the 32-bit ARM path must guard against
/// - an LBA or a tick count aliasing once it exceeds 32 bits - does not arise here.
///
/// **`nostack` is correct, and it is correct because of `sscratch`.** The trap lands on the task's
/// KERNEL stack, swapped in by the trap entry, so the user stack is untouched across the call. That
/// is a property the kernel establishes rather than one the instruction guarantees; if that latch
/// were ever removed the option would become a lie, which is why it is named here.
///
/// The caller-saved set is declared clobbered even though this kernel's trap entry currently saves
/// and restores ALL 31 registers. Relying on that would make the SDK depend on an implementation
/// detail of one handler rather than on the ABI, and a future fast path that saved less would break
/// services silently rather than at the seam.
///
/// # Safety
/// Caller must pass valid arguments for the given syscall number.
#[cfg(target_arch = "riscv64")]
#[inline]
pub(crate) unsafe fn raw_syscall(nr: u64, a0: u64, a1: u64, a2: u64) -> i64 {
    let ret: i64;
    // SAFETY: `ecall` from U-mode raises an environment-call exception, which the kernel's trap
    // vector routes to the syscall dispatcher; it services the call and returns with `a0` holding
    // the result. Every caller-saved register is declared clobbered rather than assumed to survive.
    unsafe {
        core::arch::asm!(
            "ecall",
            in("a7") nr,
            inout("a0") a0 => ret,
            inout("a1") a1 => _,
            inout("a2") a2 => _,
            lateout("a3") _,
            lateout("a4") _,
            lateout("a5") _,
            lateout("a6") _,
            lateout("t0") _,
            lateout("t1") _,
            lateout("t2") _,
            lateout("t3") _,
            lateout("t4") _,
            lateout("t5") _,
            lateout("t6") _,
            options(nostack),
        );
    }
    ret
}

#[cfg(target_arch = "x86_64")]
#[inline]
pub(crate) unsafe fn raw_syscall(nr: u64, a0: u64, a1: u64, a2: u64) -> i64 {
    let ret: i64;
    // SAFETY: `ud2` triggers a hardware #UD exception (IDT[6]) which transitions
    // to ring-0 via ud2_syscall_entry and returns via iretq.  The CPU switches
    // to kernel stack (TSS.rsp0) on the exception, so the user stack is untouched
    // - options(nostack) is correct.  ud2_syscall_entry advances RIP by 2 before
    // iretq so control resumes at the instruction after the ud2 opcode.
    unsafe {
        core::arch::asm!(
            "ud2",
            inout("rax") nr => ret,
            inout("rdi") a0 => _,
            inout("rsi") a1 => _,
            inout("rdx") a2 => _,
            lateout("rcx") _,   // used as 4th arg in ud2_syscall_entry; may be clobbered
            lateout("r10") _,   // used as scratch in ud2_syscall_entry
            lateout("r11") _,   // caller-saved; syscall_handler may modify
            lateout("r8")  _,
            lateout("r9")  _,
            options(nostack),
        );
    }
    ret
}
